### ISSUE TITLE
 Responsibilities Joomla Accessibility Team

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#20]
I think we should describe in a concise document what Joomla Accessibility Team is doing, for which the JAT is responsible. 
Here are two of my proposals for such a document. I invite you to the discussion. I apologize for my English. I hope that we will find better wording in the discussion. 

## What is Joomla Accessibility Team doing?
* We define accessibility requirements for Joomla!
* We analyze Joomla! accessibility and initiate improvements
* We analyze the accessibility of websites in joomla.org domain and initiate the elimination of barriers
* We assess the compatibility of Joomla extensions and templates with accessibility requirements.
* We help developers, designers and webmasters understand accessibility
* We help extension and templates designers to solve accessibility problems
* Let us evaluate Joomla new features in terms of accessibility
* We maintain a list of Joomla extensions and templates that meet the accessibility requirements.
* We prepare accessibility documentation of Joomla UI components
* We create guides on creating accessible content, extensions, and templates.

## Responsibilities Joomla Accessibility Team:
* Define accessibility requirements for Joomla!
* Analysing Joomla accessibility and initiating improvements
* Analyzing the accessibility of sites in joomla.org domain and initiating elimination of barriers
* Helping extension designers and templates to solve accessibility problems 
* Assessing the compatibility of Joomla extensions and templates with accessibility requirements
* Help developers, designers, and site developers to understand accessibility
* Assessing Joomla's new features in terms of accessibility
* Maintenance of Joomla extension and templates lists that meet accessibility requirements
* Preparation of documentation for the accessibility of Joomla UI components
* Developing guides on creating accessible content, extensions, and templates

**Comment by armenos** [comment]
Please stop apologizing about English, otherwise we must apologize every time.  We know it’s not our first (mother) language, for me it’s even the third 😊. Ok we know we are international a11y fanatics (some of us) and wants to make Joomla accessible. No language issues 😊 
It’s a nice list with our activities and responsibilities. Let’s discus 😊
It’s a long list, the question is that I have:
Do we have resources and time to make this happen?

I do believe that we can do it step by step. 
For now: Joomla 4 (Joomla UI components documentation and testing and supporting Joomla 4 development team)

Now my questions

## Personally I have questions on this points:
### What is Joomla Accessibility Team doing?
* We analyse the accessibility of websites in joomla.org domain and initiate the elimination of barriers 
(Comment: I don’t know if it’s what we are doing. But maybe you mean by this we report the issue, because can we eliminate it?)
* We help developers, designers and webmasters understand accessibility
(Comment: by delivering documentation?)
* We help extension and templates designers to solve accessibility problems
(Comment: by delivering documentation?)
* We maintain a list of Joomla extensions and templates that meet the accessibility requirements.
(Comment: are we talking about Joomla core or everything on JED? I think we must concentrate on the core. When we have accomplished this then we can dream about other stuff 😊)
### Responsibilities Joomla Accessibility Team:
* Helping extension designers and templates to solve accessibility problems
(Comment: once again, our theme can’t be responsible for 3rd party extensions, we must concentrate on the core of Joomla)
* Maintenance of Joomla extension and templates lists that meet accessibility requirements
(Comment: maybe in the future, is good idea. Again concentrate on the core)

**Comment by armenos** [comment]
## From my point of view the main aria to concentrate on
### Performing tests, to support developers in their work.
-	Testing of current Joomla 3.x versions and future 4.x
-	Reporting, Creating / Reporting Issues: https://github.com/joomla/joomla-cms/issues
-	Implementing Improvements
### Create documents
-	UI Components documentation: This is the description, guide, specification for developers to understand how to develop accessible software for Joomla! CMS
-	Tutorial: documentation how to keep a website accessible. For example, how to place images on a website, etc.
-	Testing: make documentation for users and developers how to test whether their website is accessible to the product.
### Guide this project
-	Team meetings
-	Making report
-	Communication to outside teams, Joomla Community
### We need Liaison to support:
-	Joomla 4 Developing team with testing and advice
-	UX Joomla team with testing and advice (for example- Jonathan is with us and I’m in there team)
Maybe you can come with some improvements?

**Comment by zwiastunsw** [comment]
1. Both my texts speak about the same, only a bit differently, in a different form. We are discussing one of them.
2. It is a proposal to describe what the JAT is supposed to deal with, not just what it is currently doing, what it is focused on.
In my opinion, we need such a description. Among other things, to look for people to perform these tasks. 
3. In this document, we should not explain how we will carry out these tasks. We should only define the tasks and responsibilities of the team. 
We should briefly, clearly and comprehensibly describe our tasks. 
4. Of course, I agree that we should now concentrate on the tasks that you are listing. But one of these tasks is to organize a team. Good, precise definition of team tasks is an important stage in team organization.

**Comment by armenos** [comment]
@zwiastunsw in that case we are thinking the same. Yes we need now to organize this all. We have much information, I hope our team members will give their opinion on this matter and then we can move on.

**Comment by chmst** [comment]
To be honest: I do not like the "responsibilities". If I am responsible for something - I have to do it, and I have to provide 100% correct results. This is not possible, because
1)  we are voluteers, not enough heads with know how - and someof us with lack of time and other priorities.
2) The topics are nor measurable or provable. 

I think the first description from @zwiastunsw  "What is Joomla Accessibility Team doing?" and what @armenos said in "From my point of view the main aria to concentrate on" are right and sufficient.

**Comment by zwiastunsw** [comment]
@chmst : I think the title is not very important. The first and the second is good. It is important how the team's tasks are defined. I am more in tune with the second way.

And yet about of responsibility: In volunteer teams, responsibility for tasks is just as important as in any other team. It is a question of trust. I trust that you will do what you commit yourself to. And if you don't manage, you'll tell us early enough to delegate the task to someone else. Only then will the team succeed.

**Comment by jonrz** [comment]
I disagree about changing "responsibilities" to something else. @zwiastunsw said well.
It's not because we are volunteers that we don't have responsibilities.
What we do is important, and if you choose to commit to it, people are counting on you.

We take only on the responsibilities of what we can deliver. There is no mandate on you taking on these responsibilities or not. It is your choice. You may choose to say "Sorry, I can't commit to do that".

And even if you commit to something that you later realize you can't deliver, you have the responsibility of passing that task on to someone else as soon as you can, because people are counting on its results.

The only ones that you don't have a choice are the ones that rule our interactions with each other, our limitations on behavior within a group. You accept the rules, so you can be part of that group as equal, where your voice is heard, and your contributions valued.

As for the numbers to make all of this happen, you are allowed to take new members on. There is a Volunteer Engagement Team that was just formed with the intent of looking for new members for groups. Talk to them and see what is possible. And if you think you can find some volunteers on your own, also let them know and ask for the rules on bringing on new volunteers.

As for 100% accurate results, as most things in life and work, you need to get them as accurate as possible according to the standards of the type of work you're doing. If you later find out something was not as accurate, acknowledge it, point it out, so either you or someone else can fix it. Some things will be fixed more than once, and that happens in companies as well, with paid employees. The gold standard is to do your best.

**Comment by seenee** [comment]
hej
czemu to zamknąłeś?

Pozdrawiam

Justyna Michallek

m. +48694599626

e. biuro@teya.pl

h. http://teya.pl/

f. https://www.facebook.com/AgencjaReklamowaTEYA



Agencja Reklamowa TEYA Justyna Michallek

Kossaka 4/10, 83-000 Pruszcz Gdański

NIP 7451581741

2018-03-17 2:41 GMT+01:00 Stefan Wajda <notifications@github.com>:
