### ISSUE TITLE
Accordion - Request for testing

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#21]
@dgt41 asked for accessibility tests:
https://joomla-projects.github.io/custom-elements/bootstrap-demo.html
Ask for test results and comments here.

**Comment by armenos** [comment]
## Panels as accordion
**Keyboard:** I could tab to Tab panel 1 and it was possible for me to navigate with arrow keys.
**Screen reader:** pronounces the Tab panels.
**Tested with:**
* Windows 10 Pro (15063.540)
* Firefox: 55.03 (32-bits)
* NVDA2: NonVisual Desktop Access 2017.3
* Color Contrast Analyser: ver.2.5.0.0

**Comment by zwiastunsw** [comment]
**Keybord support**: OK (Tab key move focus to other element, arrows keys move focus to next, previous tab)
**Screen reader**: correct annotation of the change and the status of the tabs (panels). Note: The NVDA incorrectly reports that we have one tab out of two, instead of three, but it is probably a NVDA error. ChromeVox pronounce correctly.

Tested with:
* Windows 10
* Chrome 60.0.3112.113 (64-bit)
* Firefox 55.03 (32-bit)
* NVDA 2017.3
* ChromeVox 53.0.2784.5

**Comment by chmst** [comment]
Tested with Keyboard - ok
Not tested with Screenreader
Code Inspection


role: 
The accordion is marked up as tablist - OK
The header panel is marked up as tab- OK
The content panel is marked up as tabpane- OK

**aria-expanded: Set to true when the accordion panel is expanded, otherwise set to false.
NOT OK.** 
We had a discussion on glip about that, whether aria-selected or aria-expanded must be set. In fact, it is aria-expanded:  https://github.com/joomla/accessibility/blob/master/docs/custom-elements/Widget-Accordions.md

aria-controls OK
aria-hidden: OK
aria-labelledby: OK

Not found:
**aria-disabled: If the accordion panel is expanded and is not allowed to be collapsed, then set to true.**

Not found: 
**Accordions can have several panels open: role=tablist + aria-multiselectable= true. In this case, expande="true" must be set on all open panels**
https://github.com/joomla/accessibility/blob/master/docs/custom-elements/Widget-Tabs.md
