### ISSUE TITLE
Admin menu - expected behavior

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#25]

**Comment by ylahav** [comment]
I am working on the admin main menu... before start to code or make changes I focus on checking the behaviour of Dimitris Grammatiko implementation. The following is my results:
1. Do we want a key to "jump to menu"?
2. The menu is closed
  - right arrow: next element
  - left element: previous element
  - down arrow: open the sub-menu (if any) and jump to the first sub-menu element.
  - up arrow:  open the sub-menu (if any) and jump to the last sub-menu element.
3. A sub-menu is open
  - up / down arrows: previous / next element
  -right arrow: close the menu, jump to the previous (hight level) menu element and open it (if it has one).
  - REMARK: when moving from a menu element which does not have sub-menus elements to the 'next' (or 'previous') which has sub-menus - the sub-menu are not shown (open).
            They will be opened on a click on right or left arrow ass was described above
4. let assume that the a sub-menu is shown because we used the mouse - we can use the keyboard BUT when leaving current menu / sub-menu element it is not close.
   When, for example, we on a another menu element and open its sub-menu elements with the down arrow it open it but the other (opened) menu is not close

It will be nice, if before making any change we will defined the expected behaviour and first of all I want to get you idea... Thanks, Yair

**Comment by dgrammatiko** [comment]
> 2. The menu is closed

Menu should reveal itself if only icons are displayed on keypress (arrow keys).

**Comment by zwiastunsw** [comment]
The behavior of the menu is precisely described in: [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#menu)
### Menu (parent, main)
* **Space, Enter**: 
  Opens submenu and moves focus to first item in the submenu.
* **Right Arrow**: 
  Moves focus to the next item in the menubar.
  If focus is on the last item, moves focus to the first item.
* **Left Arrow**:	
  Moves focus to the previous item in the menubar.
  If focus is on the first item, moves focus to the last item.
* **Down Arrow**:	
  Opens submenu and moves focus to first item in the submenu.
* **Up Arrow**:	
  Opens submenu and moves focus to last item in the submenu.
* **Home**:	
  Moves focus to first item in the menubar.
* **End**: 
  Moves focus to last item in the menubar.
* **Character**:	
  Moves focus to next item in the menubar having a name that starts with the typed character.
  If none of the items have a name starting with the typed character, focus does not move.

### Submenu

* **Space, Enter**:	
  Activates menu item, causing the link to be activated.
* **Escape**:	
  Closes submenu.
  Moves focus to parent menubar item.
* **Right Arrow**:	
  If focus is on an item with a submenu, opens the submenu and places focus on the first item.
  If focus is on an item that does not have a submenu: 
  - Closes submenu.
  - Moves focus to next item in the menubar.
  - Opens submenu of newly focused menubar item, keeping focus on that parent menubar item.
* **Left Arrow**:	
  Closes submenu and moves focus to parent menu item.
  If parent menu item is in the menubar, also: 
  - moves focus to previous item in the menubar.
  - Opens submenu of newly focused menubar item, keeping focus on that parent menubar item.
* **Down Arrow**:	
  Moves focus to the next item in the submenu.
  If focus is on the last item, moves focus to the first item.
* **Up Arrow**:	
  Moves focus to previous item in the submenu.
  If focus is on the first item, moves focus to the last item.
* **Home**:	
  Moves focus to the first item in the submenu.
* **End** 
  Moves focus to the last item in the submenu.
* **Character**:	
  Moves focus to the next item having a name that starts with the typed character.
  If none of the items have a name starting with the typed character, focus does not move.

**Comment by ylahav** [comment]
@zwiastunsw - thanks :-)
