### ISSUE TITLE
What is accessibility

### ISSUE THREAD

**Issue by brianteeman** [joomla/accessibility#9]
> Web accessibility means designing and developing your website so that people with disabilities can perceive, understand, navigate, and interact with, and contribute to, the Web.

I really hate this description. Accessibilty should be about ensuring that **everyone** can use the web

>The power of the Web is in its universality. Access by everyone regardless of disability is an essential aspect.
— Tim Berners-Lee, W3C Director and inventor of the World Wide Web

**Comment by chmst** [comment]
Think you are right, but how would you say it?

Web accessibility means designing and developing your website so everyone, regardless of  disabilities can perceive ...  ?

Writing such a "official" statement also is is a linguistic problem for all of us who are not native speakers (and maybe for some native speakers as well).  I use to say "Accessible for all" because I hate the term "barrier free", but am not sure if this is correct English. Web Accessibility means that no one is excluded from using the Web.

**Comment by brianteeman** [comment]
1. I would just use the Tim Berbers Lee quote

2. Most of my native English speaking a11y colleagues love the German barrier free. It is so much more meaningful to say without barriers instead of making it accessible

**Comment by zwiastunsw** [comment]
10 years ago the Web rolled up the discussion, which can be summarized in the words Accessibility vs Universality.
Of course, we can go back to this discussion again and take it today in the world of Joomla. The effect - as I think - will be similar, as in that discussion. 
In fact, there are no contradictions between the two approaches. And the dispute about the definition is not needed. We will not solve it satisfactorily for everyone. So the official definition of the W3C is a legitimate choice here.

Personally, I am also inclined to believe that accessibility means accessibility for everyone. In the Accessibility Statement project, we referred to the meaning of the word Joomla as "all together", we emphasize that "Inclusion is in our heart" and the universal importance of accessibility.

In the introductory article What is Accessibility, we will clarify this point.

**Comment by armenos** [comment]
But some uses inclusive design, much popular word now 😊
Here in The Netherlands barrier free is also used, but it say nothing. For me it sounds meaningless.
I’m saying this because someone who doesn’t know this topic, he or she will not get it. Barrier free from what? It’s the same with accessibility 
Ya the quote of Tim Berbers Lee is much better, but it’s a quote not a word. :)

Stefan already gives a good point about our approach as JAT. 
Jonathan helped us with a nice text, you can read it here: https://volunteers.joomla.org/teams/accessibility-team
So what’s the goal of this, to have a common, understandable communication in Joomla project?
We are almost ready to publish Accessibility Statement, see if you can help.
https://github.com/joomla/accessibility/issues/12

**Comment by armenos** [comment]
Guys is it ok if I close this issue?
